### ISSUE TITLE
Conv1d in decoder instead of linear

### ISSUE THREAD

**Issue by Archelunch** [CODEJIN/SPEECHSPLIT#1]
Hi!
Why do you use Conv1d layer in the decoder? Because in the original paper authors use linear layer

**Comment by CODEJIN** [comment]
Hi,

Conv1d layer with kernel size 1 is same to linear layer except channel location (Conv1x1: dim 1, Linear: dim 2). In PyTorch, convolution calculations require '[Batch, Channels, Width] (convolution 1D)' or [Batch, Channels, Height, Width] (convolution 2D) tensor shape, but linear(full connection) calculation requires '[Batch, *, Features(channels)]'. To maintain the consistency, I usually prefer to remain the tensor shape like [Batch, Channels, Width]. Thus, I used the Conv1d.

Thanks,

Heejo

**Comment by Archelunch** [comment]
okay
thanks
