### ISSUE TITLE
How to make Wav_Path_for_Inference_Replication??

### ISSUE THREAD

**Issue by c1a1o1** [CODEJIN/SPEECHSPLIT#3]
How to make Wav_Path_for_Inference_Replication??

**Comment by CODEJIN** [comment]
Basically, the format of the text files for inference while training is 'TSV'. To test independent inputs among rhyme, content, and pitch, currently, the inserted paths are also separate. If you just want to try to transfer one speaker to another, please set the same `source path` as the rhyme, content, and pitch path and just change speaker id.

**Comment by c1a1o1** [comment]
Thanks a lot!
